protected/controllers/OrderController.php
<?php

class OrderController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';



public function accessRules() {
	return array(
			array('allow',
			      'actions'=>array('index','view', 'purchase', 'verifypurchase','checkin','authorizeCode'),
				'roles'=>array('*'),

				),
			array('allow', 
				'actions'=>array('minicreate', 'create','update'),
				'roles'=>array('UserCreator'),
				),
			array('allow', 
			      'actions'=>array('index','admin','delete','verifypurchase','view','authorizeCode','checkin'),
				'users'=>array('admin'),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
	  if(Yii::app()->request->isAjaxRequest)	{	    
            Yii::app()->clientScript->scriptMap['jquery.js'] = false;
            Yii::app()->clientScript->scriptMap['jquery.min.js'] = false
;            Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
            echo CJSON::encode(array(
				     'status' => 'failure',
				     'content' => $this->renderPartial("view", array(
										     'model' => $this->loadModel($id)),true,true)));
	    
	  } else {
	    $this->render('view',array(
				       'model'=>$this->loadModel($id),
				       ));
	  }
	}

	public function actionAuthorizeCode($id) {

	  $channel_id = $id;
	  if (!$channel = Channel::model()->findByPk($channel_id)) throw new Exception("No such channel {$channel_id} found!");
	  if (!empty($_POST["Order"]["code"])) $code = $_POST["Order"]["code"];
	  else return false;


	  if ($order = Order::model()->validateCode($code)) {

	      $channel = $order->channel;
	      $channel->addAccess($order);

	      $this->renderPartial('refresh', array("channel" => $channel,"order" => $order),false, true);


	    } else {

	    $this->renderPartial("invalidcode", array());


	    }
	
	}
	    	    

	public function actionVerifyPurchase($id) {

	  $channel_id = $id;

	  $order = Order::model();

	  $this->performAjaxValidation($order, 'order-form');	  

	  
	  if (!$channel = Channel::model()->findByPk($channel_id)) throw new Exception("No such channel {$channel_id} found!");
	  if ($channel->priceclass->amount == 0) throw new Exception("Channel is free, no purchase possibl");
	  $order = Order::model();
	  $order->channel_id = $id;

	  if(Yii::app()->request->isAjaxRequest)	{	    
	  $this->renderPartial("order", array("model" => $order, "channel" => $channel));
	  }else {
	  $this->render("order", array("model" => $order, "channel" => $channel));
	  }

	}
	public function actionCheckIn() {

	  $ref = $_REQUEST["REFERENCE"];
	  $order = Order::model()->find("id={$ref}");
	  if ((int)$order->status ==2) {
	    $this->render("alreadyused", array("model" => $order));
	    exit();
	  }

	  $get = $_GET;
	  if ($order->validatePurchase($get)) {
	    $channel = $order->channel;
	    $channel->addAccess($order);
	    $order->status = $_REQUEST["STATUS"];
	    $get = $_REQUEST;
	    $order->transaction_data = serialize($get);

	    $order->save();

	    $this->render("success", array("model" => $order));
	  } else {
	    $this->render("failure", array("model" => $order));
	  }
	  
	}


	public function actionPurchase($id, $email="") {
	  

	  if (empty($email)) $email = $_POST["Order"]["email"];
	  if (empty($email)) return false;
	  
	  $channel_id = $id;


	  if (!$channel = Channel::model()->findByPk($channel_id)) throw new Exception("No such channel {$channel_id} found!");
	  $order = Order::model()->purchase($email,$channel_id);
	  $xml = $order->prepareCheckoutPurchase();

	  if(Yii::app()->request->isAjaxRequest)	{	    
	    $this->renderPartial("banks", array("xml" => $xml, "link" => $link, "order" => $order));
	  }
	  else 
	    $this->render("banks", array("xml" => $xml, "link" => $link, "order" => $order));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Order;

		$this->performAjaxValidation($model, 'order-form');

		if(isset($_POST['Order']))
		{
			$model->attributes=$_POST['Order'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		$this->performAjaxValidation($model, 'order-form');

		if(isset($_POST['Order']))
		{
			$model->attributes=$_POST['Order'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Order');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Order('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Order']))
			$model->attributes=$_GET['Order'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

}

protected/controllers/PriceclassController.php
<?php

class PriceclassController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

public function filters() {
	return array(
			'accessControl', 
			);
}

public function accessRules() {
	return array(
			array('allow',
				'actions'=>array('index','view'),
				'roles'=>array('*'),
				),
 			array('allow', 
			      'actions'=>array('admin','delete','create','update','view'),
				'users'=>array('admin'),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Priceclass;
		Yii::app()->user->setFlash('success', '<strong>Hintaluokka luotu!</strong>');
        $this->performAjaxValidation($model, 'priceclass-form');

		if(isset($_POST['Priceclass']))
		{
			$model->attributes=$_POST['Priceclass'];
			if($model->save())
				$this->redirect(array('update','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

        $this->performAjaxValidation($model, 'priceclass-form');

		if(isset($_POST['Priceclass']))
		{
			$model->attributes=$_POST['Priceclass'];
			if($model->save()) {
		Yii::app()->user->setFlash('success', '<strong>Hintaluokka päivitetty!</strong>');
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Priceclass');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Priceclass('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Priceclass']))
			$model->attributes=$_GET['Priceclass'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}


}

protected/controllers/VideoController.php
<?php

class VideoController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Video;

        $this->performAjaxValidation($model, 'video-form');

		if(isset($_POST['Video']))
		{
			$model->attributes=$_POST['Video'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
	
		$this->actionVideo($id);

	}

	public function actionWatch($id)
	{
		$model=$this->loadModel($id);
		$partial = "player";
		$movie = $model->title;



        if (isset($_POST['ajax']) && $_POST['ajax'] === 'media-videos-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }



        if (Yii::app()->request->isAjaxRequest) {
            // Stop jQuery from re-initialization
            Yii::app()->clientScript->scriptMap['jquery.js'] = false;
            Yii::app()->clientScript->scriptMap['jquery.min.js'] = false
;            Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
            echo CJSON::encode(array(
                'status' => 'failure',
                'content' => $this->renderPartial($partial, array(
                    'model' => $model, 'url' => $url_prefix . $model->filename, 'movie' => $model->title), true, true),
            ));
            exit;
        }
	
	}

	public function actionVideo($id) {

	  $model = Video::model()->findByPk($id);
	  if (isset($_POST['ajax']) && $_POST['ajax'] === 'media-videos-form') {
            echo CActiveForm::validate($model);
	    Yii::app()->end();
	  }


	  if (isset($_POST['Video'])) {
            $model->attributes = $_POST['Video'];
            $model->profile = (int) $_POST["Video"]["profile"];

            if ($model->validate()) {
	      if ($model->save()) {

		if (Yii::app()->request->isAjaxRequest) {

		  // Stop jQuery from re-initialization
		  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		  Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
		  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;

		  echo CJSON::encode(array(
					   'status' => 'success',
					   'content' => "Created successfully",
					   ));
		  exit;
		}

		return;
	      }
            }
	  }


	  if (Yii::app()->request->isAjaxRequest) {
            // Stop jQuery from re-initialization
	    Yii::app()->clientScript->scriptMap['jquery.js'] = false;
	    Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;
		  Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
            echo CJSON::encode(array(
				     'status' => 'failure',
				     'content' => $this->renderPartial('_video_file_details', array(
													      'model' => $model), true, true),
				     ));
            exit;
	  }
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Video');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Video('search');

		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Video']))
			$model->attributes=$_GET['Video'];
		$this->render('admin',array(
			'model'=>$model,
		));
	
	}
}

protected/views/layouts/api.php
<? echo $content; ?>

protected/views/layouts/channel.php
		<?php echo $content; ?>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-22">
	<div id="content">

<?php $this->widget('bootstrap.widgets.TbAlert', array(
'block'=>true, // display a larger alert block?
  'fade'=>true, // use transitions?
  'closeText'=>'&times;', // close link text - if set to false, no close link is displayed
  'alerts'=>array( // configurations per alert type
		  'success'=>array('block'=>true, 'fade'=>true, 'closeText'=>'&times;'), // success, info, warning, error or danger
		   ),
  )); ?>

		<?php echo $content; ?>
	</div><!-- content -->
</div>

</div>
<?php $this->endContent(); ?>

protected/views/layouts/json.php
<?


echo utf8_encode(json_encode((array)$data));
?>

protected/views/layouts/main.php
<?php 
/* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/jquery-ui.css" media="screen, projection" />
	<link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>

	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->
<?	Yii::app()->clientScript->registerScriptFile('/js/site/jquery.ui.min.js', CClientScript::POS_HEAD); 
	  Yii::app()->clientScript->registerScriptFile("/js/site/elfinder.min.js", CClientScript::POS_END);?>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>




	<div id="main-menu">
   <?php

   $user = Yii::app()->user->data()->id;
if ($user) {
  if (Yii::app()->user->id == 1)   $channels = Channel::model()->findAll();
  else $channels = Channel::model()->findAll("user_id={$user}");
foreach ((array)$channels as $channel) {
  $channel_array[] = array("url" => "/channel/update/" . $channel->id, "label" => $channel->name);
}

}


?>
    <?php $this->widget('bootstrap.widgets.TbNavbar', array(
							    'type'=>'inverse', // null or 'inverse'

							    'brand'=>'Citystream',
							    'brandUrl'=>'/',
							    'collapse'=>true, // requires bootstrap-responsive.css
							    'items'=>array(
									   array(
										 'class'=>'bootstrap.widgets.TbMenu',
										 'items'=>array(
												array('label'=>'Soittolistat', 'url'=>array('/playlist/admin'), 'visible'=>!Yii::app()->user->isGuest),
												array('label'=>'Videot', 'url'=>array('/video/admin'), 'visible'=>!Yii::app()->user->isGuest),

												array('label'=>'Kirjasto', 'url'=>array('/site/file_manager', 'view' => 'shop'),  'visible'=>!Yii::app()->user->isGuest, 'linkOptions' => array('class' =>'update-dialog-open-link', 'data-update-dialog-title' => 'Kirjasto', 'data-update-dialog-width' => 860)),

												),
										 ),

									   array(
										 'class'=>'bootstrap.widgets.TbMenu',
										 'htmlOptions'=>array('class'=>'pull-right'),
										 'items'=>array(

												'---',
												array('label'=>'Kanavat','visible'=>!Yii::app()->user->isGuest, 'url'=>'#', 'items'=>array_merge((array)$channel_array, array(
																							   '---',
																		      array('label'=>'Kanavien hallinnointi'),

																							   array('label'=>'Kaikki kanavat', 'url'=>array('/channel/admin')),																		      array('label'=>'Soittolistat', 'url'=>array('/playlist/admin')),

																										       ))),
												array('label'=>'Asetukset', 'visible'=>!Yii::app()->user->isGuest, 'url'=>'#', 'items'=>array(
																							       array('label'=>'Omat tiedot', 'url'=>array("/user/user/view/id/" . Yii::app()->user->data()->id)),
																							       array('label'=>'Hintaluokat', 'url'=>array('/priceclass/admin'), 'visible' => Yii::app()->user->id == 1),

																							       array('label'=>'Tilaukset', 'url'=>array('/order/admin'), 'visible' => Yii::app()->user->id == 1),
																							       array('label'=>'Käyttäjät','visible' => !Yii::app()->user->isGuest, 'url'=>array('user/user/admin')),																		      '---',
																							       array('label'=>'Vaihda salasana', 'url'=>array('/user/user/changePassword',)),
																		      )),
												array('label'=>'Kirjaudu', 'url'=>array('/user/auth'), 'visible'=>Yii::app()->user->isGuest),
												array('label'=>'Kirjaudu ulos ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
												),
										 ),
									   ),
							    )); ?>
<br/>

</div>
<div class="container" id="page">
	<!-- mainmenu --><br/>
	<?php if(isset($this->breadcrumbs)):?>
								 <?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
								 'links'=>$this->breadcrumbs,
															      )); ?>

			<?php endif;?>


	<?php echo $content; ?>
<? 
if (empty($title)) $title = ""; 

$this->widget('ext.EUpdateDialog.EUpdateDialog', array("dialogOptions" => array("width" => 640, "height"=> 500, "title" => $title))); ?>
	<div class="clear"></div>

	<div id="footer">
    Copyright &copy; <?php echo date('Y'); ?>  janiluuk@gmail.com<br/>

	</div><!-- footer -->

</div><!-- page -->



</body>
</html>