protected/models/PlaylistItem.php
<?php

Yii::import('application.models._base.BasePlaylistItem');

class PlaylistItem extends BasePlaylistItem
{
    /**
     * @return PlaylistItem
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'PlaylistItem|PlaylistItems', $n);
    }

}

protected/controllers/PlaylistController.php
<?php

class PlaylistController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
	$model = $this->loadModel($id);
	        $this->performAjaxValidation($model, 'playlist-form');
	
		if(isset($_POST['Playlist']))
		{
			$model->attributes=$_POST['Playlist'];
			Yii::app()->user->setFlash('success', '<strong>Soittolista tallennettu!</strong>');
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'id' => $id
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 */

	public function actionCreate()
	{
		$model=new Playlist;

        $this->performAjaxValidation($model, 'playlist-form');

		if(isset($_POST['Playlist']))
		{
			$model->attributes=$_POST['Playlist'];
			$model->user_id = Yii::app()->user->data()->id;
			Yii::app()->user->setFlash('success', '<strong>Soittolista luotu!</strong>');
			if($model->save()) {
			  if (Yii::app()->request->isAjaxRequest) {

			    // Stop jQuery from re-initialization
			    Yii::app()->clientScript->scriptMap['jquery.js'] = false;
			    Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;
			    echo $model->id;
			    Yii::app()->end();

			  } else {
			    $this->redirect(array('view','id'=>$model->id));
			  }
			}
		}

		if (Yii::app()->request->isAjaxRequest) {

		  // Stop jQuery from re-initialization
		  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;
		$this->renderPartial('_miniform',array(
			'model'=>$model,
					     ));
 
		} else
		$this->render('create',array(
			'model'=>$model,

					     ));
	}

	public function actionAssign($id, $id2) {
			  // Stop jQuery from re-initialization
		  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;


	  $playlist = Playlist::model()->find("id={$id}");
	  $channel = Channel::model()->find("id={$id2}");
	  $channel->playlist_id = $playlist->id;
	  $channel->save();

	  $playlistItem = new PlaylistItem;

	  $this->renderPartial("playlist", array("model" => $playlistItem, "id" => $id), false, true);
	  
	}


	public function actionAddVideo($id, $id2) {
			  // Stop jQuery from re-initialization
		  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;


	  $playlist = Playlist::model()->find("id={$id}");
	  $video = Video::model()->find("id={$id2}");
	  
	 
	  $playlistItem = new PlaylistItem();
	  $playlistItem->playlist_id = $id;
	  $playlistItem->video_id = $id2;
	  $playlistItem->save();
	  $this->renderPartial("playlist", array("model" => $playlistItem, "id" => $id), false, true);
	  
	}


	public function actionDelVideo($id, $id2) {
			  // Stop jQuery from re-initialization
	  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
	  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;


	  $playlistItem = PlaylistItem::model()->find("id={$id2}");
	  $playlistItem->delete();
	  $playlistItem = new PlaylistItem();
	  
	  $this->renderPartial("playlist", array("model" => $playlistItem, "id" => $id), false, true);


	}

	public function actionDeleteVideo($id, $id2) {
			  // Stop jQuery from re-initialization
	  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
	  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;


	  $video = Video::model()->find("id={$id2}");
	  $video->delete();
	  Yii::app()->user->setFlash('success', '<strong>Video poistettu!</strong>');
	  if ($playlistItem = PlaylistItem::model()->findAll("video_id={$id2}")) {
	    foreach ((array)$playlistItem as $item) {
	      $item->delete();
	    }
	  }
	  $playlistItem = new PlaylistItem;

	  $this->renderPartial("playlist", array("model" => $playlistItem, "id" => $id), false, true);



	}

	public function actionGeneratePlaylist($id) {

	  $model = new Playlist;

	  $playlist = Playlist::model()->with("Items")->find("t.id={$id}",array('order'=>'order'));

	  $playlist->generatePlaylistFile();
	  Yii::app()->user->setFlash('success', '<strong>Soittolista luotu!</strong>');


	  
	  $this->render("playlist", array("model" => $model), false, true);

	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

        $this->performAjaxValidation($model, 'playlist-form');

		if(isset($_POST['Playlist']))
		{
			$model->attributes=$_POST['Playlist'];
			Yii::app()->user->setFlash('success', '<strong>Soittolista tallennettu!</strong>');
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}


	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Playlist');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Playlist('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Playlist']))
			$model->attributes=$_GET['Playlist'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id="", $modelClass="")
	{
		$model=Playlist::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model, $form=null)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='playlist-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/PlaylistItemController.php
<?php

class PlaylistItemController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new PlaylistItem;

        $this->performAjaxValidation($model, 'playlist-item-form');

		if(isset($_POST['PlaylistItem']))
		{
			$model->attributes=$_POST['PlaylistItem'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}


	public function actionSort()
	{
	  if (isset($_POST['items']) && is_array($_POST['items'])) {
	    $i = 0;
	    foreach ($_POST['items'] as $item) {
	      $project = PlaylistItem::model()->findByPk($item);
	      $project->order = $i;
	      $project->save();
	      $i++;
	    }
	  }
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

        $this->performAjaxValidation($model, 'playlist-item-form');

		if(isset($_POST['PlaylistItem']))
		{
			$model->attributes=$_POST['PlaylistItem'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('PlaylistItem');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new PlaylistItem('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['PlaylistItem']))
			$model->attributes=$_GET['PlaylistItem'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=PlaylistItem::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='playlist-item-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/VideoController.php
<?php

class VideoController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Video;

        $this->performAjaxValidation($model, 'video-form');

		if(isset($_POST['Video']))
		{
			$model->attributes=$_POST['Video'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
	
		$this->actionVideo($id);

	}

	public function actionWatch($id)
	{
		$model=$this->loadModel($id);
		$partial = "player";
		$movie = $model->title;



        if (isset($_POST['ajax']) && $_POST['ajax'] === 'media-videos-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }



        if (Yii::app()->request->isAjaxRequest) {
            // Stop jQuery from re-initialization
            Yii::app()->clientScript->scriptMap['jquery.js'] = false;
            Yii::app()->clientScript->scriptMap['jquery.min.js'] = false
;            Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
            echo CJSON::encode(array(
                'status' => 'failure',
                'content' => $this->renderPartial($partial, array(
                    'model' => $model, 'url' => $url_prefix . $model->filename, 'movie' => $model->title), true, true),
            ));
            exit;
        }
	
	}

	public function actionVideo($id) {

	  $model = Video::model()->findByPk($id);
	  if (isset($_POST['ajax']) && $_POST['ajax'] === 'media-videos-form') {
            echo CActiveForm::validate($model);
	    Yii::app()->end();
	  }


	  if (isset($_POST['Video'])) {
            $model->attributes = $_POST['Video'];
            $model->profile = (int) $_POST["Video"]["profile"];

            if ($model->validate()) {
	      if ($model->save()) {

		if (Yii::app()->request->isAjaxRequest) {

		  // Stop jQuery from re-initialization
		  Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		  Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
		  Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;

		  echo CJSON::encode(array(
					   'status' => 'success',
					   'content' => "Created successfully",
					   ));
		  exit;
		}

		return;
	      }
            }
	  }


	  if (Yii::app()->request->isAjaxRequest) {
            // Stop jQuery from re-initialization
	    Yii::app()->clientScript->scriptMap['jquery.js'] = false;
	    Yii::app()->clientScript->scriptMap['jquery.min.js'] = false;
		  Yii::app()->clientScript->scriptMap['bootstrap.js'] = false;
            echo CJSON::encode(array(
				     'status' => 'failure',
				     'content' => $this->renderPartial('_video_file_details', array(
													      'model' => $model), true, true),
				     ));
            exit;
	  }
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Video');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Video('search');

		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Video']))
			$model->attributes=$_GET['Video'];
		$this->render('admin',array(
			'model'=>$model,
		));
	
	}
}

protected/views/playlistItem/_form.php
<div class="form">
    <?php
    /** @var AweActiveForm $form */
    $form = $this->beginWidget('ext.AweCrud.components.AweActiveForm', array(
    'id' => 'playlist-item-form',
    'enableAjaxValidation' => true,
    'enableClientValidation'=> false,
    )); ?>

    <p class="note">
        <?= Yii::t('AweCrud.app', 'Fields with') ?> <span class="required">*</span>
        <?= Yii::t('AweCrud.app', 'are required') ?>.    </p>

    <?= $form->errorSummary($model) ?>

                            <?= $form->dropDownListRow($model, 'playlist_id', CHtml::listData(Playlist::model()->findAll(), 'id', Playlist::representingColumn())) ?>
                        <?= $form->dropDownListRow($model, 'video_id', CHtml::listData(Video::model()->findAll(), 'id', Video::representingColumn())) ?>
                        <?= $form->textFieldRow($model, 'order', array('class' => 'span5')) ?>
                <div class="form-actions">
                <?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? Yii::t('AweCrud.app', 'Create') : Yii::t('AweCrud.app', 'Save'),
		)); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
			//'buttonType'=>'submit',
			'label'=> Yii::t('AweCrud.app', 'Cancel'),
			'htmlOptions' => array('onclick' => 'javascript:history.go(-1)')
		)); ?>
    </div>

    <?php $this->endWidget(); ?>
</div>

protected/views/playlistItem/_search.php
<?php
/** @var AweActiveForm $form */
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

<?= $form->textFieldRow($model, 'id', array('class' => 'span5')); ?>

<?= $form->dropDownListRow($model, 'playlist_id', CHtml::listData(Playlist::model()->findAll(), 'id', Playlist::representingColumn())); ?>

<?= $form->dropDownListRow($model, 'video_id', CHtml::listData(Video::model()->findAll(), 'id', Video::representingColumn())); ?>

<?= $form->textFieldRow($model, 'order', array('class' => 'span5')); ?>

<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array(
			'type' => 'primary',
			'label' => Yii::t('AweCrud.app', 'Search'),
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/playlistItem/_view.php
<div class="view">

    
                        
                    <?php if (!empty($data->playlist->playlist_name)): ?>
                    <div class="field">
            <div class="field_name">
                <b><?= CHtml::encode($data->getAttributeLabel('playlist_id')) ?>:</b>
            </div>
            <div class="field_value">
                                <?= CHtml::encode($data->playlist->playlist_name) ?>
                            </div>
        </div>

                    <?php endif; ?>
                                    
                    <?php if (!empty($data->video->title)): ?>
                    <div class="field">
            <div class="field_name">
                <b><?= CHtml::encode($data->getAttributeLabel('video_id')) ?>:</b>
            </div>
            <div class="field_value">
                                <?= CHtml::encode($data->video->title) ?>
                            </div>
        </div>

                    <?php endif; ?>
                                    
                    <?php if (!empty($data->order)): ?>
                    <div class="field">
            <div class="field_name">
                <b><?= CHtml::encode($data->getAttributeLabel('order')) ?>:</b>
            </div>
            <div class="field_value">
                                <?= CHtml::encode($data->order) ?>
                            </div>
        </div>

                    <?php endif; ?>
                        </div>

protected/views/playlistItem/admin.php
<?php
$this->breadcrumbs=array(
	'Playlist Items'=>array('index'),
	Yii::t('AweCrud.app', 'Manage'),
);

$this->menu=array(
	array('label' => Yii::t('AweCrud.app', 'List') . ' ' . PlaylistItem::label(2), 'icon' => 'list', 'url' => array('index')),
	array('label' => Yii::t('AweCrud.app', 'Create') . ' PlaylistItem', 'icon' => 'plus', 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('playlist-item-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<fieldset>
    <legend>
        <?= Yii::t('AweCrud.app', 'Manage') ?> <?= PlaylistItem::label(2) ?>    </legend>

<?= CHtml::link('<i class="icon-search"></i> ' . Yii::t('AweCrud.app', 'Advanced Search'), '#', array('class' => 'search-button btn')) ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id' => 'playlist-item-grid',
    'type' => 'striped condensed',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
        'id',
        array(
                    'name' => 'playlist_id',
                    'value' => 'isset($data->playlist) ? $data->playlist : null',
                    'filter' => CHtml::listData(Playlist::model()->findAll(), 'id', Playlist::representingColumn()),
                ),
        array(
                    'name' => 'video_id',
                    'value' => 'isset($data->video) ? $data->video : null',
                    'filter' => CHtml::listData(Video::model()->findAll(), 'id', Video::representingColumn()),
                ),
        'order',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>
</fieldset>

protected/views/playlistItem/create.php
<?php
$this->breadcrumbs=array(
	$model->label(2) => array('index'),
	'Create',
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.PlaylistItem::label(2), 'icon' => 'list', 'url' => array('index')),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend><?= Yii::t('AweCrud.app', 'Create') ?> PlaylistItem</legend>
    <?php echo $this->renderPartial('_form', array('model'=>$model)); ?></fieldset>

protected/views/playlistItem/index.php
<?php
$this->breadcrumbs = array(
	'Playlist Items',
);

$this->menu = array(
    array('label' => Yii::t('AweCrud.app', 'Create') . ' PlaylistItem', 'icon' => 'plus', 'url' => array('create')),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend>
        <?= Yii::t('AweCrud.app', 'List') ?> <?= PlaylistItem::label(2) ?>    </legend>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>
</fieldset>

protected/views/playlistItem/update.php
<?php
$this->breadcrumbs=array(
	$model->label(2) => array('index'),
	Yii::t('app', $model->id) => array('view', 'id'=>$model->id),
	Yii::t('AweCrud.app', 'Update'),
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.PlaylistItem::label(2), 'icon' => 'list', 'url' => array('index')),
	// array('label' => Yii::t('AweCrud.app', 'Create').' PlaylistItem', 'icon' => 'plus', 'url' => array('create')),
	//array('label' => Yii::t('AweCrud.app', 'View'), 'icon' => 'eye-open', 'url'=>array('view', 'id' => $model->id)),
	array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
    array('label' => Yii::t('AweCrud.app', 'Delete'), 'icon' => 'trash', 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => Yii::t('AweCrud.app', 'Are you sure you want to delete this item?'))),
);
?>

<fieldset>
    <legend><?= Yii::t('AweCrud.app', 'Update') ?> PlaylistItem <?= CHtml::encode($model) ?></legend>
<?php echo $this->renderPartial('_form',array('model'=>$model)); ?></fieldset>

protected/views/playlistItem/view.php
<?php
$this->breadcrumbs=array(
	'Playlist Items'=>array('index'),
	$model->id,
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.PlaylistItem::label(2), 'icon' => 'list', 'url' => array('index')),
    array('label' => Yii::t('AweCrud.app', 'Create').' PlaylistItem', 'icon' => 'plus', 'url' => array('create')),
	array('label' => Yii::t('AweCrud.app', 'Update'), 'icon' => 'pencil', 'url' => array('update', 'id' => $model->id)),
    array('label' => Yii::t('AweCrud.app', 'Delete'), 'icon' => 'trash', 'url' => '#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => Yii::t('AweCrud.app', 'Are you sure you want to delete this item?'))),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend><?= Yii::t('AweCrud.app', 'View') ?> PlaylistItem <?= CHtml::encode($model) ?></legend>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data' => $model,
	'attributes' => array(
        'id',
        array(
			'name'=>'playlist_id',
			'value'=>($model->playlist !== null) ? CHtml::link($model->playlist, array('/playlist/view', 'id' => $model->playlist->id)).' ' : null,
			'type'=>'html',
		),
        array(
			'name'=>'video_id',
			'value'=>($model->video !== null) ? CHtml::link($model->video, array('/video/view', 'id' => $model->video->id)).' ' : null,
			'type'=>'html',
		),
        'order',
	),
)); ?>
</fieldset>