protected/controllers/PriceclassController.php
<?php

class PriceclassController extends AweController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

public function filters() {
	return array(
			'accessControl', 
			);
}

public function accessRules() {
	return array(
			array('allow',
				'actions'=>array('index','view'),
				'roles'=>array('*'),
				),
 			array('allow', 
			      'actions'=>array('admin','delete','create','update','view'),
				'users'=>array('admin'),
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Priceclass;
		Yii::app()->user->setFlash('success', '<strong>Hintaluokka luotu!</strong>');
        $this->performAjaxValidation($model, 'priceclass-form');

		if(isset($_POST['Priceclass']))
		{
			$model->attributes=$_POST['Priceclass'];
			if($model->save())
				$this->redirect(array('update','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

        $this->performAjaxValidation($model, 'priceclass-form');

		if(isset($_POST['Priceclass']))
		{
			$model->attributes=$_POST['Priceclass'];
			if($model->save()) {
		Yii::app()->user->setFlash('success', '<strong>Hintaluokka päivitetty!</strong>');
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Priceclass');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Priceclass('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Priceclass']))
			$model->attributes=$_GET['Priceclass'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}


}

protected/views/priceclass/_form.php
<div class="form">
    <?php
    /** @var AweActiveForm $form */
    $form = $this->beginWidget('ext.AweCrud.components.AweActiveForm', array(
    'id' => 'priceclass-form',
    'enableAjaxValidation' => true,
    'enableClientValidation'=> false,
    )); ?>



    <?= $form->errorSummary($model) ?>

<div class="fl span-5">                            <?= $form->textFieldRow($model, 'name', array('class' => 'span-5', 'maxlength' => 64)) ?></div>
<div class="fl span-2">                        <?= $form->textFieldRow($model, 'amount', array('class' => 'fl span-2')) ?></div>

<div class="fl span-3"> <?= $form->dropDownListRow($model, 'type', CHtml::listData(Priceclass::getTypes(),"id","name"), array('class' => 'fl span-3')) ?></div>



                <div class="clear form-actions">
                <?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? Yii::t('AweCrud.app', 'Luo uusi') : Yii::t('AweCrud.app', 'Tallenna'),
		)); ?>
    </div>

    <?php $this->endWidget(); ?>
</div>

protected/views/priceclass/_search.php
<?php
/** @var AweActiveForm $form */
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

<?= $form->textFieldRow($model, 'id', array('class' => 'span5')); ?>

<?= $form->textFieldRow($model, 'name', array('class' => 'span5', 'maxlength' => 64)); ?>

<?= $form->textFieldRow($model, 'amount', array('class' => 'span5')); ?>

<?= $form->textFieldRow($model, 'type', array('class' => 'span5')); ?>

<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array(
			'type' => 'primary',
			'label' => Yii::t('AweCrud.app', 'Search'),
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/priceclass/_view.php
<div class="view">

    
                        
                    <?php if (!empty($data->name)): ?>
                    <div class="field">
            <div class="field_name">
                <b><?= CHtml::encode($data->getAttributeLabel('name')) ?>:</b>
            </div>
            <div class="field_value">
                                <?= CHtml::encode($data->name) ?>
                            </div>
        </div>

                    <?php endif; ?>
                                    
                    <?php if (!empty($data->amount)): ?>
                    <div class="field">
            <div class="field_name">
                <b><?= CHtml::encode($data->getAttributeLabel('amount')) ?>:</b>
            </div>
            <div class="field_value">
                                <?= CHtml::encode($data->amount) ?>
                            </div>
        </div>

                    <?php endif; ?>
                                    
                    <?php if (!empty($data->type)): ?>
                    <div class="field">
            <div class="field_name">
                <b><?= CHtml::encode($data->getAttributeLabel('type')) ?>:</b>
            </div>
            <div class="field_value">
                                <?= CHtml::encode($data->type) ?>
                            </div>
        </div>

                    <?php endif; ?>
                        </div>

protected/views/priceclass/admin.php
<?php
$this->breadcrumbs=array(
	'Hintaluokat'=>array('index'),
	Yii::t('AweCrud.app', 'Kaikki'),
);

$this->menu=array(
	array('label' => Yii::t('AweCrud.app', 'List') . ' ' . Priceclass::label(2), 'icon' => 'list', 'url' => array('index')),
	array('label' => Yii::t('AweCrud.app', 'Create') . ' Priceclass', 'icon' => 'plus', 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('priceclass-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<fieldset>
    <legend>
        <?= Yii::t('AweCrud.app', 'Hintaluokat') ?>   </legend>

<?= CHtml::link('<i class="icon-plus"></i> ' . Yii::t('AweCrud.app', 'Lisää uusi'), '/priceclass/create', array('class' => 'add-button btn-success btn')) ?>
<?= CHtml::link('<i class="icon-search"></i> ' . Yii::t('AweCrud.app', 'Tarkka haku'), '#', array('class' => 'search-button btn')) ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id' => 'priceclass-grid',
    'type' => 'striped condensed',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
        'name',
        array(
					'name' => 'amount',
					'value' => '$data->amount . " €"',
	      ),

        array(
					'name' => 'type',
					'value' => 'Priceclass::getType($data->type)',
					'filter' => array('0' => Yii::t('AweCrud.app', 'Ilmainen'), '1' => Yii::t('AweCrud.app', 'Maksullinen')),
					),

	
	array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'buttons'=>array(	      	'delete','update',	 		'view' => array('visible' => function() { return false; }),)


		      ),
			   )));
?>
</fieldset>

protected/views/priceclass/create.php
<?php
$this->breadcrumbs=array(
	"Hintaluokat" => array('index'),
	'Luo uusi',
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.Priceclass::label(2), 'icon' => 'list', 'url' => array('index')),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend><?= Yii::t('AweCrud.app', 'Luo uusi') ?> hintaluokka</legend>
    <?php echo $this->renderPartial('_form', array('model'=>$model)); ?></fieldset>

protected/views/priceclass/index.php
<?php
$this->breadcrumbs = array(
	'Priceclasses',
);

$this->menu = array(
    array('label' => Yii::t('AweCrud.app', 'Create') . ' Priceclass', 'icon' => 'plus', 'url' => array('create')),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend>
        <?= Yii::t('AweCrud.app', 'List') ?> <?= Priceclass::label(2) ?>    </legend>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>
</fieldset>

protected/views/priceclass/update.php
<?php
$this->breadcrumbs=array(
			 "Hintaluokat" => array('admin'),
	Yii::t('app', $model->name) => array('view', 'id'=>$model->id),
	Yii::t('AweCrud.app', 'Muokkaa'),
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.Priceclass::label(2), 'icon' => 'list', 'url' => array('index')),
	// array('label' => Yii::t('AweCrud.app', 'Create').' Priceclass', 'icon' => 'plus', 'url' => array('create')),
	//array('label' => Yii::t('AweCrud.app', 'View'), 'icon' => 'eye-open', 'url'=>array('view', 'id' => $model->id)),
	array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
    array('label' => Yii::t('AweCrud.app', 'Delete'), 'icon' => 'trash', 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => Yii::t('AweCrud.app', 'Are you sure you want to delete this item?'))),
);
?>

<fieldset>
    <legend><?= CHtml::encode($model) ?></legend>
<?php echo $this->renderPartial('_form',array('model'=>$model)); ?></fieldset>

protected/views/priceclass/view.php
<?php
$this->breadcrumbs=array(
	'Priceclasses'=>array('index'),
	$model->name,
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.Priceclass::label(2), 'icon' => 'list', 'url' => array('index')),
    array('label' => Yii::t('AweCrud.app', 'Create').' Priceclass', 'icon' => 'plus', 'url' => array('create')),
	array('label' => Yii::t('AweCrud.app', 'Update'), 'icon' => 'pencil', 'url' => array('update', 'id' => $model->id)),
    array('label' => Yii::t('AweCrud.app', 'Delete'), 'icon' => 'trash', 'url' => '#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => Yii::t('AweCrud.app', 'Are you sure you want to delete this item?'))),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend><?= Yii::t('AweCrud.app', 'View') ?> Priceclass <?= CHtml::encode($model) ?></legend>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data' => $model,
	'attributes' => array(
        'id',
        'name',
        'amount',
        'type',
	),
)); ?>
</fieldset>